package com.example.sjh.database.greenDao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.sjh.gcsjdemo.entity.Remind;
import com.example.sjh.gcsjdemo.entity.ChatMessage;

import com.example.sjh.database.greenDao.db.RemindDao;
import com.example.sjh.database.greenDao.db.ChatMessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig remindDaoConfig;
    private final DaoConfig chatMessageDaoConfig;

    private final RemindDao remindDao;
    private final ChatMessageDao chatMessageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        remindDaoConfig = daoConfigMap.get(RemindDao.class).clone();
        remindDaoConfig.initIdentityScope(type);

        chatMessageDaoConfig = daoConfigMap.get(ChatMessageDao.class).clone();
        chatMessageDaoConfig.initIdentityScope(type);

        remindDao = new RemindDao(remindDaoConfig, this);
        chatMessageDao = new ChatMessageDao(chatMessageDaoConfig, this);

        registerDao(Remind.class, remindDao);
        registerDao(ChatMessage.class, chatMessageDao);
    }
    
    public void clear() {
        remindDaoConfig.clearIdentityScope();
        chatMessageDaoConfig.clearIdentityScope();
    }

    public RemindDao getRemindDao() {
        return remindDao;
    }

    public ChatMessageDao getChatMessageDao() {
        return chatMessageDao;
    }

}
