package com.example.sjh.database.greenDao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.sjh.gcsjdemo.entity.Remind;

import com.example.sjh.database.greenDao.db.RemindDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig remindDaoConfig;

    private final RemindDao remindDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        remindDaoConfig = daoConfigMap.get(RemindDao.class).clone();
        remindDaoConfig.initIdentityScope(type);

        remindDao = new RemindDao(remindDaoConfig, this);

        registerDao(Remind.class, remindDao);
    }
    
    public void clear() {
        remindDaoConfig.clearIdentityScope();
    }

    public RemindDao getRemindDao() {
        return remindDao;
    }

}
